version: '3.7'
services:
  frontend:
    image: react-nginx-image-new:latest
    ports:
      - "80"
    deploy:  
      replicas: 2
      placement:
       constraints:
          - node.role == worker     
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      
        
