version: '3.7'
services:
  frontend:
    image: react-nginx:1.0.0
    ports:
      - "80"
    deploy:  
      replicas: 2
      placement:
       constraints:
          - node.role == worker     
      resources:
        limits:
          cpus: "0.2"
          memory: 100M
      
        
