version: '3.7'
services:
  frontend:
    image: localhost:8080/nirav1611/react-nginx-image-new
    ports:
      - "80"
    deploy:  
      replicas: 2
      placement:
       constraints:
          - node.role == worker     
      resources:
        limits:
          cpus: "0.2"
          memory: 100M
      
        
